version: "3"
services:
  postfixadmin-fetchmail:
    container_name: postfixadmin-fetchmail
    image: docker.io/volkerraschek/postfixadmin-fetchmail:latest
    environment:
    - DATABASE_TYPE=${DATABASE_TYPE}
    - DATABASE_USER=${DATABASE_USER}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_HOST=${DATABASE_HOST}
    - DATABASE_PORT=${DATABASE_PORT}
    - DATABASE_NAME=${DATABASE_NAME}
    network_mode: host
    privileged: true
